CREATE SCHEMA IF NOT EXISTS public;


CREATE TABLE IF NOT EXISTS public.movies
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    rating   DOUBLE PRECISION,
    order_id BIGINT,
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price DOUBLE PRECISION,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

alter table public.movies drop constraint if exists "FK_MOVIES_ON_ORDER";
ALTER TABLE public.movies
    ADD CONSTRAINT FK_MOVIES_ON_ORDER FOREIGN KEY (order_id) REFERENCES public.orders (id);



